version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: ./docker/entrypoint-dev.sh
    command: yarn dev:debug
    env_file: ./.env
    ports:
      - 9229:9229
    volumes:
      - .:/home/bot/moshi
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.4
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=moshi
