FROM node:17 as builder

WORKDIR /home/bot/moshi

COPY . .

RUN yarn --omit=dev
RUN yarn build
RUN rm -rf src/

FROM node:17-alpine

RUN apk update && \
    apk add ffmpeg python3 libtool autoconf automake make g++

RUN wget -O /usr/local/bin/yt-dlp  https://github.com/yt-dlp/yt-dlp/releases/download/2023.02.17/yt-dlp
    
RUN chmod +x /usr/local/bin/yt-dlp

WORKDIR /home/bot/moshi

COPY --from=builder /home/bot/moshi .

CMD [ "yarn", "start" ]
